"""PDF report generation for a single disaster-severity analysis.

Builds a clean one-page (occasionally two-page) assessment report with
`fpdf2` — header, timestamp, the original + Grad-CAM images, the prediction
and confidence, a full class-probability table, the Average Drop % quality
metric, and model info. Used by `app/app.py`'s "Download Report" button.

Kept dependency-light and ASCII-only in text so it renders with fpdf2's core
Helvetica font (no external TTF needed).
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, Optional, Union

import numpy as np
from fpdf import FPDF
from PIL import Image

from utils.zonemap import CLASS_COLORS

# RGB tuples for fpdf (which wants 0-255 ints, not hex).
_RGB = {k: tuple(int(v.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4)) for k, v in CLASS_COLORS.items()}
_INK = (33, 37, 43)
_MUTED = (110, 118, 129)
_LINE = (210, 214, 220)


def _as_pil(img: Union[Image.Image, np.ndarray]) -> Image.Image:
    if isinstance(img, Image.Image):
        return img.convert("RGB")
    arr = np.asarray(img)
    if arr.dtype != np.uint8:
        arr = np.uint8(np.clip(arr, 0, 255))
    return Image.fromarray(arr).convert("RGB")


class _Report(FPDF):
    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_MUTED)
        self.cell(
            0, 8,
            "Generated by Project43-DisasterSeverity  |  C-DAC Mohali",
            align="C",
        )


def build_report_pdf(
    original_img: Union[Image.Image, np.ndarray],
    gradcam_img: Union[Image.Image, np.ndarray],
    pred_class: str,
    confidence: float,
    all_probs: Dict[str, float],
    average_drop: Optional[float] = None,
    model_info: str = "EfficientNetB0 (5.3M params, 224x224)  |  96.94% val accuracy",
) -> bytes:
    """Render a single-analysis PDF report and return it as bytes.

    Args:
        original_img: The analysed image (PIL Image or uint8/float RGB array).
        gradcam_img: The Grad-CAM overlay (PIL Image or uint8/float RGB array).
        pred_class: Predicted class name (one of CLASS_NAMES).
        confidence: Top-class probability in [0, 1].
        all_probs: {class_name: probability} for all four classes.
        average_drop: Optional Grad-CAM Average Drop % quality metric.
        model_info: One-line model description for the footer block.

    Returns:
        The PDF file contents as `bytes`, ready for `st.download_button`.
    """
    pdf = _Report(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pw = pdf.w - pdf.l_margin - pdf.r_margin

    # ── Header banner ────────────────────────────────────────────────
    pdf.set_fill_color(23, 33, 54)
    pdf.rect(0, 0, pdf.w, 26, style="F")
    pdf.set_xy(pdf.l_margin, 7)
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, "Disaster Severity Assessment Report", align="L")
    pdf.set_xy(pdf.l_margin, 16)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(200, 208, 220)
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 6, f"Generated: {stamp}   |   EfficientNet + Grad-CAM   |   AIDERv2", align="L")

    pdf.ln(20)

    # ── Images side by side ──────────────────────────────────────────
    img_w = (pw - 8) / 2
    img_h = img_w  # square-ish
    y0 = pdf.get_y()
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_INK)
    pdf.cell(img_w, 6, "Original Image", align="C")
    pdf.cell(8, 6, "", align="C")
    pdf.cell(img_w, 6, "Grad-CAM Explanation", align="C")
    pdf.ln(7)
    y_img = pdf.get_y()
    pdf.image(_as_pil(original_img), x=pdf.l_margin, y=y_img, w=img_w, h=img_h)
    pdf.image(_as_pil(gradcam_img), x=pdf.l_margin + img_w + 8, y=y_img, w=img_w, h=img_h)
    pdf.set_y(y_img + img_h + 6)

    # ── Prediction banner ────────────────────────────────────────────
    rgb = _RGB.get(pred_class, _INK)
    pdf.set_fill_color(*rgb)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(pw, 12, f"  Predicted: {pred_class}    Confidence: {confidence * 100:.1f}%",
             border=0, align="L", fill=True)
    pdf.ln(16)

    # ── Probability table ────────────────────────────────────────────
    pdf.set_text_color(*_INK)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Class Probabilities", align="L")
    pdf.ln(9)

    col1, col2 = pw * 0.45, pw * 0.55
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 242, 245)
    pdf.set_draw_color(*_LINE)
    pdf.cell(col1, 8, "  Class", border=1, fill=True)
    pdf.cell(col2, 8, "  Probability", border=1, fill=True)
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 9)
    for cls in all_probs:
        prob = float(all_probs[cls])
        crgb = _RGB.get(cls, _MUTED)
        pdf.set_text_color(*crgb)
        pdf.cell(col1, 7, f"  {cls}", border=1)
        # simple bar + number
        bar_max = col2 - 40
        pdf.set_text_color(*_INK)
        x_bar = pdf.get_x()
        y_bar = pdf.get_y()
        pdf.set_fill_color(*crgb)
        pdf.rect(x_bar + 2, y_bar + 1.5, max(0.5, bar_max * prob), 4, style="F")
        pdf.cell(col2, 7, f"{'':40s}{prob * 100:.2f}%", border=1, align="R")
        pdf.ln(7)

    pdf.ln(4)

    # ── Metrics + model info ─────────────────────────────────────────
    pdf.set_text_color(*_INK)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Explanation Quality & Model", align="L")
    pdf.ln(9)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_MUTED)
    drop_txt = f"{average_drop:.1f}%" if average_drop is not None else "n/a"
    pdf.multi_cell(
        pw, 6,
        f"Grad-CAM Average Drop %: {drop_txt}\n"
        "  (higher = the highlighted region was more causal to the prediction)\n"
        f"Model: {model_info}\n"
        "Classes: Earthquake, Fire, Flood, Normal",
        border=0,
    )

    out = pdf.output()
    return bytes(out)
